name: funfy_scanner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^0.5.2
  shared_preferences: ^2.0.6
  dotted_decoration: ^2.0.0
  http: ^0.13.3
  flutter_rating_bar: ^4.0.0
  flutter_svg: any
  sliding_up_panel: ^2.0.0+1
  flutter_spinkit: ^5.0.0
  get: ^4.3.8
  flash: ^2.0.1
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  stripe_sdk: ^5.0.0-nullsafety.0
  provider: ^6.0.0
  flutter_launcher_icons: ^0.9.2
  webviewx: ^0.2.0
  hexcolor: ^2.0.5
  html: ^0.15.0
#  flutter_html: 2.0.0
  flutter_widget_from_html: ^0.7.0
  connectivity: ^3.0.6



dev_dependencies:

  flutter_app_name: ^0.1.0
flutter_app_name:
  name: "Funfy Booking Scan"

  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/IconApp.png"
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/editPen.png
    - assets/images/logout.png
    - assets/images/defaultImage.png
    - assets/locale/localization_es.json
    - assets/locale/localization_en.json
    - assets/images/language.svg
    - assets/images/help.svg
    - assets/images/about us.svg
    - assets/images/translationicon.png
    - assets/images/onSettings.svg





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AbrilFatFace
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
        - asset: assets/fonts/Product Sans Bold.ttf
        - asset: assets/fonts/Product Sans Regular.ttf
    - family: Gretaros
      fonts:
        - asset: assets/fonts/Gretaros-Regular.ttf




  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
